- name: "Edit systemd timesyncd.conf setting: {{ description }}"
  ansible.builtin.blockinfile:
    path: "{{ cfg_time_linux_timesyncd_conf_filepath }}"
    insertafter: >-
      ^\[Time\]$
    block: "{{ setting_line }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ description }}"
    create: false
    state: present
  become: true
  become_user: root
  notify: "restart-systemd-timesyncd"

