- name: "Call out to {{ geo_ip_uri }} to determine timezone based on IP addr location"
  block:
    - name: "Set 'tz' fact by calling out to geo IP"
      ansible.builtin.include_tasks: func/set_tz_from_geo_ip.yml
  rescue:
    - name: "SECOND TRY - Set 'tz' fact by calling out to geo IP"
      ansible.builtin.include_tasks: func/set_tz_from_geo_ip.yml
  when: time_zone_tz_name == 'auto'

- name: "Define tz-name-string to time_zone_tz_name var '{{ time_zone_tz_name }}'"
  ansible.builtin.set_fact:
    tz: "{{ time_zone_tz_name }}"
  when: time_zone_tz_name != 'auto'

- name: "Set the system time zone to tz-name-string '{{ tz }}'"
  community.general.timezone:
    name: "{{ tz }}"
  become: true
  become_user: root

